plt.figure(figsize=(7,5))
plt.scatter(actual_sfr, predicted_sfr, alpha=0.7, label='Predicted vs Actual')
plt.plot([0,2.5], [0,2.5], 'r--', label='Ideal Fit')
plt.xlabel('Actual SFR')
plt.ylabel('Predicted SFR')
plt.title('Predicted vs. Actual Star Formation Rate (SFR)')
plt.legend()
plt.grid(True)
plt.show()
print('Displayed scatter plot of predicted vs. actual SFR.')
