import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd

# Load the data generated by the Origins script
df = pd.read_csv("validated_curves_data.csv")

fig = plt.figure(figsize=(12, 9))
ax = fig.add_subplot(111, projection='3d')

# Plot each curve as a point, colored by rank
colors = {0: 'k', 1: 'b', 2: 'g', 3: 'r'}
for rank, group in df.groupby('rank'):
   ax.scatter(group['log_delta'], group['log_cond'], group['rank'],
               c=colors.get(rank, 'y'), label=f'Rank {rank}', s=50)

# Draw filaments based on regulator similarity
for i in range(len(df)):
   for j in range(i + 1, len(df)):
       reg_diff = abs(df.iloc[i]['regulator'] - df.iloc[j]['regulator'])
       if reg_diff < 5000: # Threshold for connection
           ax.plot([df.iloc[i]['log_delta'], df.iloc[j]['log_delta']],
                   [df.iloc[i]['log_cond'], df.iloc[j]['log_cond']],
                   [df.iloc[i]['rank'], df.iloc[j]['rank']],
