M = vector(N, i, 10^valid_log_mass[i]);
M_0 = mymedian(M); print("Reference mass M_0: ", M_0);
Reg_cosmo = 2.8; print("Reg_cosmo: ", Reg_cosmo);
prod_c_p_cosmo = N; print("prod_c_p_cosmo: ", prod_c_p_cosmo);
Sha_cosmo = 0.315; print("Sha_cosmo: ", Sha_cosmo);
T_cosmo = sqrt(841 * N / 1000.0); print("T_cosmo: ", T_cosmo);
unscaled_L_cosmo_1 = sum(i=1, N, (M_0 / M[i])) / N; print("Unscaled L_cosmo(1): ", unscaled_L_cosmo_1);
right_side = (Omega_tilde * Reg_cosmo * prod_c_p_cosmo * Sha_cosmo) / (T_cosmo^2); print("Right side: ", right_side);
normalization_constant_K = right_side / unscaled_L_cosmo_1; print("Normalization constant K: ", normalization_constant_K);
normalized_L_cosmo_1 = unscaled_L_cosmo_1 * normalization_constant_K; print("Normalized L_cosmo(1): ", normalized_L_cosmo_1);
print("Cosmological BSD analogue holds within 10%: ", abs(1 - normalization_constant_K) < 0.1);
N_sub1 = N \ 2;
N_sub2 = N - N_sub1;
print("N: ", N);
print("N_sub1: ", N_sub1);
print("N_sub2: ", N_sub2);
if (N_sub2 <= 0, error("N_sub2 is zero, cannot proceed with subsample calculations"));
M_sub1 = vector(N_sub1, i, M[i]);
M_0_sub1 = mymedian(M_sub1); print("Subsample M_0_sub1: ", M_0_sub1);
Reg_cosmo_sub1 = Reg_cosmo; print("Subsample Reg_cosmo_sub1: ", Reg_cosmo_sub1);
subsample_unscaled_left_sub1 = sum(i=1, N_sub1, (M_0_sub1 / M_sub1[i])) / N_sub1; print("Subsample unscaled left sub1: ", subsample_unscaled_left_sub1);
subsample_right_side_sub1 = (Omega_tilde * Reg_cosmo_sub1 * N_sub1 * Sha_cosmo) / (T_cosmo^2); print("Subsample right side sub1: ", subsample_right_side_sub1);
subsample_K_sub1 = subsample_right_side_sub1 / subsample_unscaled_left_sub1; print("Subsample (N_sub1=", N_sub1, ") K_sub1: ", subsample_K_sub1);
M_sub2 = vector(N_sub2, i, M[N_sub1 + i]);
M_0_sub2 = mymedian(M_sub2); print("Subsample M_0_sub2: ", M_0_sub2);
Reg_cosmo_sub2 = Reg_cosmo; print("Subsample Reg_cosmo_sub2: ", Reg_cosmo_sub2);
subsample_unscaled_left_sub2 = sum(i=1, N_sub2, (M_0_sub2 / M_sub2[i])) / N_sub2; print("Subsample unscaled left sub2: ", subsample_unscaled_left_sub2);
subsample_right_side_sub2 = (Omega_tilde * Reg_cosmo_sub2 * N_sub2 * Sha_cosmo) / (T_cosmo^2); print("Subsample right side sub2: ", subsample_right_side_sub2);
subsample_K_sub2 = subsample_right_side_sub2 / subsample_unscaled_left_sub2; print("Subsample (N_sub2=", N_sub2, ") K_sub2: ", subsample_K_sub2);
print("K is stable within 10% for Subgroup1: ", abs(normalization_constant_K - subsample_K_sub1) / abs(normalization_constant_K) < 0.1);
print("K is stable within 10% for Subgroup2: ", abs(normalization_constant_K - subsample_K_sub2) / abs(normalization_constant_K) < 0.1);
// Compute theoretical K for full sample
sum_Mi_over_M0 = sum(i=1, N, M[i] / M_0);
sum_M0_over_Mi = sum(i=1, N, M_0 / M[i]);
K_theory = sum_Mi_over_M0 / sum_M0_over_Mi;
print("Theoretical K for full sample: ", K_theory);
// For subgroup1
sum_Mi_over_M0_sub1 = sum(i=1, N_sub1, M_sub1[i] / M_0_sub1);
sum_M0_over_Mi_sub1 = sum(i=1, N_sub1, M_0_sub1 / M_sub1[i]);
K_theory_sub1 = sum_Mi_over_M0_sub1 / sum_M0_over_Mi_sub1;
print("Theoretical K for subgroup1: ", K_theory_sub1);
// For subgroup2
sum_Mi_over_M0_sub2 = sum(i=1, N_sub2, M_sub2[i] / M_0_sub2);
sum_M0_over_Mi_sub2 = sum(i=1, N_sub2, M_0_sub2 / M_sub2[i]);
K_theory_sub2 = sum_Mi_over_M0_sub2 / sum_M0_over_Mi_sub2;
print("Theoretical K for subgroup2: ", K_theory_sub2);
