from sklearn.neighbors import KernelDensity
kde = KernelDensity(kernel='gaussian', bandwidth=0.35).fit(projected_vectors)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * Field evaluated on Cartesian grid:
X, Y, Z = np.meshgrid(xvals, yvals, zvals)
coords = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T
entropy_field = -kde.score_samples(coords).reshape(X.shape)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * Gradient computed using NumPy’s
 np.gradient() to derive ∇𝑺
