lines = readstr("C:/temp/filtered_log_mass.txt");
start = 0;
for (i=1, #lines, if (strtrim(lines[i]) == "log_mass = [", start = i; break));
if (start == 0, error("Header not found"));
end = 0;
for (i=#lines, 1, -1, if (strtrim(lines[i]) == "];", end = i; break));
if (end == 0, error("Footer not found"));
if (end <= start + 1, error("No data lines"));
numbers = vector(end - start - 1, i, eval(strtrim(lines[start + i])));
      * log_mass = numbers;
