/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionRouteImport } from './routes/action'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as CohomologyRouteImport } from './routes/cohomology'
import { Route as DynamicsRouteImport } from './routes/dynamics'
import { Route as ExperimentRouteImport } from './routes/experiment'
import { Route as HubbleRouteImport } from './routes/hubble'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as TheoryRouteImport } from './routes/theory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionRoute = ActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const CohomologyRoute = CohomologyRouteImport.update({
  id: '/cohomology',
  path: '/cohomology',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicsRoute = DynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentRoute = ExperimentRouteImport.update({
  id: '/experiment',
  path: '/experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const HubbleRoute = HubbleRouteImport.update({
  id: '/hubble',
  path: '/hubble',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/catalog': typeof CatalogRoute
  '/charter': typeof CharterRoute
  '/cohomology': typeof CohomologyRoute
  '/dynamics': typeof DynamicsRoute
  '/experiment': typeof ExperimentRoute
  '/hubble': typeof HubbleRoute
  '/projection': typeof ProjectionRoute
  '/theory': typeof TheoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/catalog': typeof CatalogRoute
  '/charter': typeof CharterRoute
  '/cohomology': typeof CohomologyRoute
  '/dynamics': typeof DynamicsRoute
  '/experiment': typeof ExperimentRoute
  '/hubble': typeof HubbleRoute
  '/projection': typeof ProjectionRoute
  '/theory': typeof TheoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/catalog': typeof CatalogRoute
  '/charter': typeof CharterRoute
  '/cohomology': typeof CohomologyRoute
  '/dynamics': typeof DynamicsRoute
  '/experiment': typeof ExperimentRoute
  '/hubble': typeof HubbleRoute
  '/projection': typeof ProjectionRoute
  '/theory': typeof TheoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action'
    | '/catalog'
    | '/charter'
    | '/cohomology'
    | '/dynamics'
    | '/experiment'
    | '/hubble'
    | '/projection'
    | '/theory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action'
    | '/catalog'
    | '/charter'
    | '/cohomology'
    | '/dynamics'
    | '/experiment'
    | '/hubble'
    | '/projection'
    | '/theory'
  id:
    | '__root__'
    | '/'
    | '/action'
    | '/catalog'
    | '/charter'
    | '/cohomology'
    | '/dynamics'
    | '/experiment'
    | '/hubble'
    | '/projection'
    | '/theory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionRoute: typeof ActionRoute
  CatalogRoute: typeof CatalogRoute
  CharterRoute: typeof CharterRoute
  CohomologyRoute: typeof CohomologyRoute
  DynamicsRoute: typeof DynamicsRoute
  ExperimentRoute: typeof ExperimentRoute
  HubbleRoute: typeof HubbleRoute
  ProjectionRoute: typeof ProjectionRoute
  TheoryRoute: typeof TheoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action': {
      id: '/action'
      path: '/action'
      fullPath: '/action'
      preLoaderRoute: typeof ActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohomology': {
      id: '/cohomology'
      path: '/cohomology'
      fullPath: '/cohomology'
      preLoaderRoute: typeof CohomologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamics': {
      id: '/dynamics'
      path: '/dynamics'
      fullPath: '/dynamics'
      preLoaderRoute: typeof DynamicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment': {
      id: '/experiment'
      path: '/experiment'
      fullPath: '/experiment'
      preLoaderRoute: typeof ExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubble': {
      id: '/hubble'
      path: '/hubble'
      fullPath: '/hubble'
      preLoaderRoute: typeof HubbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionRoute: ActionRoute,
  CatalogRoute: CatalogRoute,
  CharterRoute: CharterRoute,
  CohomologyRoute: CohomologyRoute,
  DynamicsRoute: DynamicsRoute,
  ExperimentRoute: ExperimentRoute,
  HubbleRoute: HubbleRoute,
  ProjectionRoute: ProjectionRoute,
  TheoryRoute: TheoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
