for(k=1, #z_bins - 1, {
  z_min = z_bins[k];
  z_max = z_bins[k + 1];
  bin_indices = select(i -> z_filtered[i] >= z_min && z_filtered[i] < z_max, vector(#z_filtered, i, i));
  if (#bin_indices == 0, next);
  sfr_bin = vector(#bin_indices, j, sfr_filtered[bin_indices[j]]);
  median_sfr = compute_median(sfr_bin);
  high_sfr_indices = select(i -> sfr_filtered[i] > median_sfr, bin_indices);
  low_sfr_indices = select(i -> sfr_filtered[i] <= median_sfr, bin_indices);
  log_mass_high_sfr = vector(#high_sfr_indices, j, log_mass_filtered[high_sfr_indices[j]]);
  log_mass_low_sfr = vector(#low_sfr_indices, j, log_mass_filtered[low_sfr_indices[j]]);
  K_high = compute_K_theory(log_mass_high_sfr);
  skew_high = compute_skewness(log_mass_high_sfr);
  K_low = compute_K_theory(log_mass_low_sfr);
  skew_low = compute_skewness(log_mass_low_sfr);
  mean_high = sum(i=1, #log_mass_high_sfr, log_mass_high_sfr[i]) / #log_mass_high_sfr;
  sd_high = sqrt(sum(i=1, #log_mass_high_sfr, (log_mass_high_sfr[i] - mean_high)^2) / (#log_mass_high_sfr - 1));
  kurt_high = compute_kurtosis(log_mass_high_sfr);
  mean_low = sum(i=1, #log_mass_low_sfr, log_mass_low_sfr[i]) / #log_mass_low_sfr;
  sd_low = sqrt(sum(i=1, #log_mass_low_sfr, (log_mass_low_sfr[i] - mean_low)^2) / (#log_mass_low_sfr - 1));
  kurt_low = compute_kurtosis(log_mass_low_sfr);
  print("z: ", z_min, " to ", z_max);
  print("high_sfr: K_theory = ", K_high, ", skewness = ", skew_high, ", mean = ", mean_high, ", sd = ", sd_high, ", kurtosis = ", kurt_high);
  print("low_sfr: K_theory = ", K_low, ", skewness = ", skew_low, ", mean = ", mean_low, ", sd = ", sd_low, ", kurtosis = ", kurt_low);
