E = EllipticCurve([-1706, 6320])
Omega = E.period_lattice().real_period()
Reg = E.regulator()
Tamagawa = prod(E.tamagawa_numbers())
Sha_estimate = 5.71614727018219 / (Omega * Reg * Tamagawa)
print(Omega, Reg, Tamagawa, Sha_estimate)
